blank_issues_enabled: false
contact_links:
  - name: Programe.new related issues
    url: https://github.com/stackblitz/bolt.new/issues/new/choose
    about: Report issues related to Programe.new (not Programe.ai)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Programe.ai users.
